### ISSUE TITLE
Would appreciate attribution

### ISSUE THREAD

**Issue by FarazzShaikh** [wass08/r3f-objects-dissolve#1]
Hey bud, thanks for adding this shader to git, I think it would be helpful to many more people this way. 

However I’d really appreciate a link back to my original [Twitter post](https://x.com/cantBeFaraz/status/1678007542817882112?s=46) and [CodeSandbox](https://codesandbox.io/s/green-resonance-5fgz3d?file=/src/DissolveMaterial.tsx) in the Readme and the shader source so people are aware of where this came from

Thanks again, keep up the good work 🙏

**Comment by wass08** [comment]
Hey mate, sorry didn't see this until now. Added to the readme, thanks to you for the great work! 🙌
